/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Menu;

import javax.swing.JOptionPane;
import java.sql.SQLException;

/**
 *
 * @author domin
 */
public class Login_User extends javax.swing.JFrame {

    /**
     * Creates new form Login_User
     */
    public Login_User() {
        initComponents();
        //Centrar el formulario
        this.setLocationRelativeTo(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        panel_fondo = new javax.swing.JPanel();
        TaskMaster = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtUser = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel3 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        btnAcceso = new javax.swing.JButton();
        btnOlvidasteContraseña = new javax.swing.JButton();
        txtPass = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        panel_fondo.setBackground(new java.awt.Color(102, 102, 102));
        panel_fondo.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        panel_fondo.setPreferredSize(new java.awt.Dimension(330, 380));
        panel_fondo.setLayout(null);

        TaskMaster.setBackground(new java.awt.Color(102, 102, 102));
        TaskMaster.setFont(new java.awt.Font("Eras Bold ITC", 0, 18)); // NOI18N
        TaskMaster.setForeground(new java.awt.Color(255, 255, 255));
        TaskMaster.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/asistente-de-robot.png"))); // NOI18N
        TaskMaster.setText("TaskMaster");
        TaskMaster.setBorder(null);
        TaskMaster.setBorderPainted(false);
        TaskMaster.setContentAreaFilled(false);
        TaskMaster.setDefaultCapable(false);
        TaskMaster.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TaskMasterActionPerformed(evt);
            }
        });
        panel_fondo.add(TaskMaster);
        TaskMaster.setBounds(40, 30, 220, 70);

        jLabel1.setFont(new java.awt.Font("Eras Bold ITC", 0, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Usuario:");
        panel_fondo.add(jLabel1);
        jLabel1.setBounds(70, 160, 130, 17);

        jLabel2.setFont(new java.awt.Font("Eras Bold ITC", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Iniciar Sesion");
        panel_fondo.add(jLabel2);
        jLabel2.setBounds(100, 120, 130, 22);

        txtUser.setBackground(new java.awt.Color(102, 102, 102));
        txtUser.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtUser.setBorder(null);
        txtUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtUserActionPerformed(evt);
            }
        });
        panel_fondo.add(txtUser);
        txtUser.setBounds(70, 180, 180, 16);

        jSeparator1.setForeground(new java.awt.Color(255, 255, 255));
        panel_fondo.add(jSeparator1);
        jSeparator1.setBounds(70, 200, 180, 10);

        jSeparator2.setForeground(new java.awt.Color(255, 255, 255));
        panel_fondo.add(jSeparator2);
        jSeparator2.setBounds(70, 260, 180, 10);

        jLabel3.setFont(new java.awt.Font("Eras Bold ITC", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Contraseña:");
        panel_fondo.add(jLabel3);
        jLabel3.setBounds(70, 220, 130, 17);

        jButton1.setBackground(new java.awt.Color(102, 102, 102));
        jButton1.setFont(new java.awt.Font("Eras Bold ITC", 0, 14)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Registrarse");
        jButton1.setBorder(null);
        jButton1.setBorderPainted(false);
        jButton1.setContentAreaFilled(false);
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton1.setDefaultCapable(false);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        panel_fondo.add(jButton1);
        jButton1.setBounds(190, 320, 120, 20);

        btnAcceso.setBackground(new java.awt.Color(102, 102, 102));
        btnAcceso.setFont(new java.awt.Font("Eras Bold ITC", 0, 14)); // NOI18N
        btnAcceso.setForeground(new java.awt.Color(255, 255, 255));
        btnAcceso.setText("Iniciar Sesion");
        btnAcceso.setBorder(null);
        btnAcceso.setBorderPainted(false);
        btnAcceso.setContentAreaFilled(false);
        btnAcceso.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnAcceso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAccesoActionPerformed(evt);
            }
        });
        panel_fondo.add(btnAcceso);
        btnAcceso.setBounds(10, 320, 140, 17);

        btnOlvidasteContraseña.setBackground(new java.awt.Color(102, 102, 102));
        btnOlvidasteContraseña.setForeground(new java.awt.Color(153, 255, 102));
        btnOlvidasteContraseña.setText("¿Olvidaste la contraseña?");
        btnOlvidasteContraseña.setBorder(null);
        btnOlvidasteContraseña.setBorderPainted(false);
        btnOlvidasteContraseña.setContentAreaFilled(false);
        btnOlvidasteContraseña.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnOlvidasteContraseña.setDebugGraphicsOptions(javax.swing.DebugGraphics.NONE_OPTION);
        btnOlvidasteContraseña.setDefaultCapable(false);
        btnOlvidasteContraseña.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOlvidasteContraseñaActionPerformed(evt);
            }
        });
        panel_fondo.add(btnOlvidasteContraseña);
        btnOlvidasteContraseña.setBounds(100, 270, 170, 23);

        txtPass.setBackground(new java.awt.Color(102, 102, 102));
        txtPass.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtPass.setBorder(null);
        panel_fondo.add(txtPass);
        txtPass.setBounds(70, 240, 180, 16);

        jScrollPane1.setViewportView(panel_fondo);

        getContentPane().add(jScrollPane1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void TaskMasterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TaskMasterActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TaskMasterActionPerformed

    private void txtUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtUserActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtUserActionPerformed
    

    private void btnAccesoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAccesoActionPerformed
       
        
        String usuario = txtUser.getText();
    char[] contraseñaChars = txtPass.getPassword();
    String contraseña = new String(contraseñaChars);

    Conexion_Users dao = new Conexion_Users();
    
    // Verificar las credenciales en la base de datos
    if (dao.validarCredenciales(usuario, contraseña)) {
        // Si las credenciales son válidas, abrir la ventana del menú principal
        Menu menu = new Menu(); // Reemplaza "Menu" con el nombre de tu clase de menú principal
        menu.setVisible(true);
        dispose(); // Cerrar la ventana actual de inicio de sesión
    } else {
        // Si las credenciales son incorrectas, mostrar un mensaje de error
        JOptionPane.showMessageDialog(this, "Credenciales incorrectas", "Error", JOptionPane.ERROR_MESSAGE);
    }
    }//GEN-LAST:event_btnAccesoActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        RegistrarUser registrarUser = new RegistrarUser();
    
    // Mostrar la ventana de registro
    registrarUser.setVisible(true);
    
    // Opcional: ocultar la ventana actual
    this.setVisible(false);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void btnOlvidasteContraseñaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOlvidasteContraseñaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnOlvidasteContraseñaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login_User.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login_User.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login_User.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login_User.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login_User().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton TaskMaster;
    private javax.swing.JButton btnAcceso;
    private javax.swing.JButton btnOlvidasteContraseña;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JPanel panel_fondo;
    private javax.swing.JPasswordField txtPass;
    private javax.swing.JTextField txtUser;
    // End of variables declaration//GEN-END:variables

}

        
               

             
