/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Menu;

/**
 *
 * @author domin
 */
public class Menu extends javax.swing.JFrame {

    /**
     * Creates new form Menu
     */
    public Menu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        panel_fondo = new javax.swing.JPanel();
        btn_Agregar_Tarea = new javax.swing.JButton();
        btn_Menu = new javax.swing.JButton();
        btn_Acerca_de = new javax.swing.JButton();
        btn_Salir1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        panel_fondo.setBackground(new java.awt.Color(102, 102, 102));
        panel_fondo.setPreferredSize(new java.awt.Dimension(300, 320));
        panel_fondo.setLayout(null);

        btn_Agregar_Tarea.setFont(new java.awt.Font("Eras Bold ITC", 0, 14)); // NOI18N
        btn_Agregar_Tarea.setForeground(new java.awt.Color(255, 255, 255));
        btn_Agregar_Tarea.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/agregar-tarea.png"))); // NOI18N
        btn_Agregar_Tarea.setText(" Agregar Tarea");
        btn_Agregar_Tarea.setBorder(null);
        btn_Agregar_Tarea.setBorderPainted(false);
        btn_Agregar_Tarea.setContentAreaFilled(false);
        btn_Agregar_Tarea.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_Agregar_Tarea.setFocusPainted(false);
        btn_Agregar_Tarea.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/img/agregar-tarea.png"))); // NOI18N
        btn_Agregar_Tarea.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/img/agregar-tarea.png"))); // NOI18N
        btn_Agregar_Tarea.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_Agregar_TareaActionPerformed(evt);
            }
        });
        panel_fondo.add(btn_Agregar_Tarea);
        btn_Agregar_Tarea.setBounds(50, 110, 200, 100);

        btn_Menu.setFont(new java.awt.Font("Eras Bold ITC", 0, 14)); // NOI18N
        btn_Menu.setForeground(new java.awt.Color(255, 255, 255));
        btn_Menu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/boton-de-inicio.png"))); // NOI18N
        btn_Menu.setText("  Menú");
        btn_Menu.setBorder(null);
        btn_Menu.setBorderPainted(false);
        btn_Menu.setContentAreaFilled(false);
        btn_Menu.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_Menu.setFocusPainted(false);
        btn_Menu.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/img/boton-de-inicio.png"))); // NOI18N
        btn_Menu.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/img/boton-de-inicio.png"))); // NOI18N
        btn_Menu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_MenuActionPerformed(evt);
            }
        });
        panel_fondo.add(btn_Menu);
        btn_Menu.setBounds(10, 10, 100, 40);

        btn_Acerca_de.setFont(new java.awt.Font("Eras Bold ITC", 0, 14)); // NOI18N
        btn_Acerca_de.setForeground(new java.awt.Color(255, 255, 255));
        btn_Acerca_de.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/informacion (1).png"))); // NOI18N
        btn_Acerca_de.setText("  Acerca de");
        btn_Acerca_de.setBorder(null);
        btn_Acerca_de.setBorderPainted(false);
        btn_Acerca_de.setContentAreaFilled(false);
        btn_Acerca_de.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_Acerca_de.setFocusPainted(false);
        btn_Acerca_de.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/img/informacion (1).png"))); // NOI18N
        btn_Acerca_de.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/img/informacion (1).png"))); // NOI18N
        btn_Acerca_de.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_Acerca_deActionPerformed(evt);
            }
        });
        panel_fondo.add(btn_Acerca_de);
        btn_Acerca_de.setBounds(150, 270, 160, 40);

        btn_Salir1.setFont(new java.awt.Font("Eras Bold ITC", 0, 14)); // NOI18N
        btn_Salir1.setForeground(new java.awt.Color(255, 255, 255));
        btn_Salir1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/cerrar-sesion (2).png"))); // NOI18N
        btn_Salir1.setText("    Salir");
        btn_Salir1.setToolTipText("");
        btn_Salir1.setBorder(null);
        btn_Salir1.setBorderPainted(false);
        btn_Salir1.setContentAreaFilled(false);
        btn_Salir1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_Salir1.setFocusPainted(false);
        btn_Salir1.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/img/cerrar-sesion (2).png"))); // NOI18N
        btn_Salir1.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/img/cerrar-sesion (2).png"))); // NOI18N
        btn_Salir1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_Salir1ActionPerformed(evt);
            }
        });
        panel_fondo.add(btn_Salir1);
        btn_Salir1.setBounds(-10, 270, 130, 40);

        jScrollPane1.setViewportView(panel_fondo);

        getContentPane().add(jScrollPane1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_MenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_MenuActionPerformed

    }//GEN-LAST:event_btn_MenuActionPerformed

    private void btn_Acerca_deActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_Acerca_deActionPerformed
        Acerca_de form = new Acerca_de();
        form.setVisible(true);
    }//GEN-LAST:event_btn_Acerca_deActionPerformed

    private void btn_Salir1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_Salir1ActionPerformed
       this.dispose();
    }//GEN-LAST:event_btn_Salir1ActionPerformed

    private void btn_Agregar_TareaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_Agregar_TareaActionPerformed
       Agregar_Tareas form = new Agregar_Tareas();
        form.setVisible(true);
 
    }//GEN-LAST:event_btn_Agregar_TareaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_Acerca_de;
    private javax.swing.JButton btn_Agregar_Tarea;
    private javax.swing.JButton btn_Menu;
    private javax.swing.JButton btn_Salir1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel panel_fondo;
    // End of variables declaration//GEN-END:variables
}
