/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Menu;
import java.sql.Connection;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import java.sql.PreparedStatement;

/**
 *
 * @author domin
 */
public class RegistrarUser extends javax.swing.JFrame {

    /**
     * Creates new form RegistrarUser
     */
    public RegistrarUser() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel1 = new javax.swing.JPanel();
        Icon_Registrarse = new javax.swing.JButton();
        label = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        txtUserNuevo = new javax.swing.JTextField();
        jSeparator2 = new javax.swing.JSeparator();
        label1 = new javax.swing.JLabel();
        txtPassNuevo = new javax.swing.JPasswordField();
        btnVolver = new javax.swing.JButton();
        btnRegistrar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(102, 102, 102));
        jPanel1.setPreferredSize(new java.awt.Dimension(340, 368));
        jPanel1.setLayout(null);

        Icon_Registrarse.setBackground(new java.awt.Color(102, 102, 102));
        Icon_Registrarse.setFont(new java.awt.Font("Eras Bold ITC", 0, 18)); // NOI18N
        Icon_Registrarse.setForeground(new java.awt.Color(255, 255, 255));
        Icon_Registrarse.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/asistente-de-robot.png"))); // NOI18N
        Icon_Registrarse.setText("Registrate");
        Icon_Registrarse.setContentAreaFilled(false);
        Icon_Registrarse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Icon_RegistrarseActionPerformed(evt);
            }
        });
        jPanel1.add(Icon_Registrarse);
        Icon_Registrarse.setBounds(40, 20, 195, 70);

        label.setFont(new java.awt.Font("Eras Bold ITC", 0, 14)); // NOI18N
        label.setForeground(new java.awt.Color(255, 255, 255));
        label.setText("Usuario:");
        jPanel1.add(label);
        label.setBounds(70, 130, 80, 17);

        jSeparator1.setBackground(new java.awt.Color(255, 255, 255));
        jSeparator1.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.add(jSeparator1);
        jSeparator1.setBounds(70, 170, 180, 10);

        txtUserNuevo.setBackground(new java.awt.Color(102, 102, 102));
        txtUserNuevo.setForeground(new java.awt.Color(255, 255, 255));
        txtUserNuevo.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtUserNuevo.setBorder(null);
        txtUserNuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtUserNuevoActionPerformed(evt);
            }
        });
        jPanel1.add(txtUserNuevo);
        txtUserNuevo.setBounds(70, 150, 180, 16);

        jSeparator2.setBackground(new java.awt.Color(255, 255, 255));
        jSeparator2.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.add(jSeparator2);
        jSeparator2.setBounds(70, 220, 180, 10);

        label1.setFont(new java.awt.Font("Eras Bold ITC", 0, 14)); // NOI18N
        label1.setForeground(new java.awt.Color(255, 255, 255));
        label1.setText("Contraseña:");
        jPanel1.add(label1);
        label1.setBounds(70, 180, 100, 17);

        txtPassNuevo.setBackground(new java.awt.Color(102, 102, 102));
        txtPassNuevo.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtPassNuevo.setBorder(null);
        txtPassNuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPassNuevoActionPerformed(evt);
            }
        });
        jPanel1.add(txtPassNuevo);
        txtPassNuevo.setBounds(70, 200, 180, 16);

        btnVolver.setBackground(new java.awt.Color(102, 102, 102));
        btnVolver.setFont(new java.awt.Font("Eras Bold ITC", 0, 14)); // NOI18N
        btnVolver.setForeground(new java.awt.Color(255, 255, 255));
        btnVolver.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/flecha-hacia-atras.png"))); // NOI18N
        btnVolver.setText("Volver");
        btnVolver.setBorder(null);
        btnVolver.setContentAreaFilled(false);
        btnVolver.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnVolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVolverActionPerformed(evt);
            }
        });
        jPanel1.add(btnVolver);
        btnVolver.setBounds(0, 290, 130, 32);

        btnRegistrar.setBackground(new java.awt.Color(102, 102, 102));
        btnRegistrar.setFont(new java.awt.Font("Eras Bold ITC", 0, 14)); // NOI18N
        btnRegistrar.setForeground(new java.awt.Color(255, 255, 255));
        btnRegistrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/documentacion.png"))); // NOI18N
        btnRegistrar.setText("Registrar");
        btnRegistrar.setBorder(null);
        btnRegistrar.setContentAreaFilled(false);
        btnRegistrar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnRegistrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrarActionPerformed(evt);
            }
        });
        jPanel1.add(btnRegistrar);
        btnRegistrar.setBounds(180, 290, 140, 40);

        jScrollPane1.setViewportView(jPanel1);

        getContentPane().add(jScrollPane1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Icon_RegistrarseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Icon_RegistrarseActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Icon_RegistrarseActionPerformed

    private void txtUserNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtUserNuevoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtUserNuevoActionPerformed

    private void btnRegistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarActionPerformed
         String usuario = txtUserNuevo.getText();
    String contraseña = new String(txtPassNuevo.getPassword());
    Login_User login_users = new Login_User();
    
    // Mostrar la ventana de registro
    login_users.setVisible(true);
    
    // Opcional: ocultar la ventana actual
    this.setVisible(false);
    
    try {
        // Llamar al método insertarUsuario para agregar el nuevo usuario a la tabla
        insertarUsuario(usuario, contraseña);
        
        // Mostrar un mensaje de éxito
        JOptionPane.showMessageDialog(this, "Usuario registrado exitosamente", "Registro Exitoso", JOptionPane.INFORMATION_MESSAGE);
    } catch (SQLException ex) {
        // Si ocurre un error al insertar el usuario, mostrar un mensaje de error
        JOptionPane.showMessageDialog(this, "Error al registrar usuario: " + ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
    }
    }//GEN-LAST:event_btnRegistrarActionPerformed
public void insertarUsuario(String usuario, String contraseña) throws SQLException {
     PreparedStatement statement = null;
    Connection conexion = null;
    
    try {
        // Establecer la conexión a la base de datos
        conexion = ConexionBD.obtenerConexion();
        System.out.println("Conexión establecida correctamente.");

        // Preparar la consulta SQL para insertar un nuevo usuario
        String sql = "INSERT INTO login_users (Usuario, Contraseña) VALUES (?, ?)";
        statement = conexion.prepareStatement(sql);
        
        // Establecer los valores de los parámetros en la consulta
        statement.setString(1, usuario);
        statement.setString(2, contraseña);
        
        // Ejecutar la consulta para insertar el nuevo usuario
        int filasInsertadas = statement.executeUpdate();
        if (filasInsertadas > 0) {
            System.out.println("Usuario creado exitosamente.");
        } else {
            System.out.println("No se insertó ningún usuario.");
        }
    } catch (SQLException ex) {
        ex.printStackTrace();
        System.out.println("Error al crear el usuario: " + ex.getMessage());
    } finally {
        // Cerrar la conexión y liberar recursos
        if (statement != null) {
            statement.close();
        }
        if (conexion != null) {
            conexion.close();
            System.out.println("Conexión cerrada correctamente.");
        }
    }
    }    
    private void btnVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVolverActionPerformed
         Login_User login = new Login_User();
        login.setVisible(true);
        dispose();

    }//GEN-LAST:event_btnVolverActionPerformed

    private void txtPassNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPassNuevoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPassNuevoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RegistrarUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RegistrarUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RegistrarUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RegistrarUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RegistrarUser().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Icon_Registrarse;
    private javax.swing.JButton btnRegistrar;
    private javax.swing.JButton btnVolver;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JLabel label;
    private javax.swing.JLabel label1;
    private javax.swing.JPasswordField txtPassNuevo;
    private javax.swing.JTextField txtUserNuevo;
    // End of variables declaration//GEN-END:variables
}
